### ISSUE TITLE
TypeError: label_binarize() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by cfgooo** [zkhku/fedsage#5]
When I try to replicate your code，I'm getting a code error in classifiers.py "TypeError: label_binarize() takes 1 positional argument but 2 were given" ，have anybody meet the same question？

**Comment by zkhku** [comment]
The cause of this error message is due to the package versions. When you run the code on your device, you can replace this line with the updated equivalent one to align with your installed packages.
________________________________
From: cfgooo ***@***.***>
Sent: Monday, February 20, 2023 8:38:43 PM
To: zkhku/fedsage ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zkhku/fedsage] TypeError: label_binarize() takes 1 positional argument but 2 were given (Issue #5)


When I try to replicate your code，I'm getting a code error in classifiers.py "TypeError: label_binarize() takes 1 positional argument but 2 were given" ，have anybody meet the same question？

**Comment by cfgooo** [comment]
您好，您发给我的邮件我已收到，谢谢，祝您生活愉快。

**Comment by cfgooo** [comment]
Thank you, I have solve the ptoblem.

**Comment by cfgooo** [comment]
I found the final problem, which is actually the python version. My pc is 3.9, but yours should be 3.8. 
Finally, thank you for your contributions to graph neural networks and federated learning, and hope to have the opportunity to learn together in the future. 谢谢您了
